config/routes.rb
Rails.application.routes.draw do
	get 'todos', to: 'todos#index'
	root 'todos#index'

	post "/todos", to: "todos#create"
	get 'todos/new'
	get '/todos/list'

	get 'todos/:id', to: 'todos#show', as: 'todo' #--> esto es el prefijo
	get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo' #--> esto es el prefijo
	patch 'todos/:id', to: 'todos#update'

	delete 'todos/:id', to: 'todos#destroy', as: 'destroy_todo' #--> esto es el prefijo

	get '/todos/:id/complete', to: 'todos#complete', as: 'complete_todo'



	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	
	def index
		@todos = Todo.all.order(description: :asc)
	end
	
	def new
		@todo = Todo.new
	end
	
	def show
		@todo = Todo.find(params[:id])
	end
	
	def edit
		@todo = Todo.find(params[:id])
	end
	
	
	def create
		@todo = Todo.new(todo_params)
		@todo.completed = false #guarda por default false
		
		if @todo.save
			redirect_to @todo, notice: 'Se creó el ToDo satisfactoriamente!!!'
		else
			redirect_to todos_new_path, notice: '******No se pudo crear el ToDo, Favor corrobore el Campo!!!!!******'
		end
	end
	
	
	def update
		@todo = Todo.find(params[:id])
		if @todo.update(todo_params)
			redirect_to root_path, notice: 'Se ha actualizado con éxito!!'
		else
			redirect_to edit_post_path(@post.id), notice: 'No se ha podido actualizar :('
		end
	end
	
	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to root_path
	end

	def complete
		@todo = Todo.find(params[:id])
		if @todo.update(completed: true)
			redirect_to root_path, notice: 'Se ha actualizado con éxito!!'
		end
	end

	def list
		@todos = Todo.all.order(description: :asc)
	end

	
	
	private
	def todo_params
		params.require(:todo).permit(:description)
	end
	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TodoApp</title>
	<%= csrf_meta_tags %>
	
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body style="margin-top: 70px;">
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href= <%= root_path %>>HOME</a>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href= <%= todos_list_path %>>Lista ToDos</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href= <%= todos_new_path %>>Crear ToDO</a>
				</li>
			</ul>
		</div>
	</nav>
	
	<%= yield %>
	
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/todos/edit.html.erb
<div class="text-center">
	<div class="col-md-8 col-xs-12 col-sm-8">
		<div class="card bg-light text-dark">
			<h1>Edición de ToDos</h1>
			
			<%= form_with(model: @todo, local: true) do |form| %>
			<%= form.label 'Descripción:' %>
			<%= form.text_field :description %>
			
			<br>
			<%= form.submit 'Guardar', class:'btn btn-success'%>
			<%= link_to  "Volver al Home", root_path, class:'btn btn-info' %>
			<br><br>
			
			<% end %>
		</div>	
	</div>
</div>

app/views/todos/index.html.erb
<div class="text-center">
	<h1 class="text-center font-weight-bold text-success">Listado de ToDos</h1>
	
	
	<!-- <div class="card bg-light mb-3" style="max-width: 10rem"> -->
		<% @todos.each do |dato| %>
		<div class="d-inline-block text-center">
			<div class="col-md-12 center-block" style="margin-bottom: 20px">
				<div class="card bg-light text-dark" style="padding-left: 20px;">
					
					<strong>DESCRIPCIÓN:</strong>   <%= dato.description %>
					<strong>ESTADO:</strong>  <%= dato.completed ? 'Completado' : 'No Completado' %> <br><br>
					
					<div>
						<%= link_to 'Mostrar', todo_path(dato), class: 'btn btn-info' %>
						<%= link_to 'Editar', edit_todo_path(dato), class: 'btn btn-warning' %>
						
						<%= link_to 'Elimnar', destroy_todo_path(dato), method: :delete, class: 'btn btn-danger' %>
						<%= link_to 'Check', complete_todo_path(dato), class: 'btn btn-success' %>	
						<br><br>
					</div>
					
				</div>
			</div>
		</div>
		
		<% end %>
		
		<br>
		
		<%= link_to  "Crear Nuevo", todos_new_path, class:'btn btn-primary' %>
	</div>

app/views/todos/list.html.erb
<div class="row">
	<div class="col-md-6 col-xs-12 col-sm-6" style="padding: 0">
		<div class="col-md-11 col-xs-12 col-sm-11" style="margin-left: 10px">
			<div class="card bg-light text-dark">
				<h3 class="text-center text-success">Todos No Completados</h3>
				<ol>
					<% @todos.map do |dato| %>
					<% if !dato.completed %>
					<li> <%= dato.description %> </li>
					<% end %>	
					<% end %>
				</ol>
			</div>
		</div>
	</div>
	
	<div class="col-md-6 col-xs-12 col-sm-6" style="padding: 0">
		<div class="col-md-11 col-xs-12 col-sm-11" style="padding: 0">
			<div class="card bg-light text-dark">
				<h3 class="text-center text-success">Todos Completados</h3>
				<ol>
					<% @todos.map do |dato| %>
					<% if dato.completed %>
					<li> <%= dato.description %> </li>
					<% end %>	
					<% end %>
				</ol>
			</div>
		</div>
	</div>
</div>

app/views/todos/new.html.erb
<strong class="text-danger"><%= notice %></strong>

<div class="text-center">
	<div class="col-md-8 col-xs-12 col-sm-8">
		<div class="card bg-light text-dark">
			<h1>Creación de ToDo</h1>
			<%= form_with(model: @todo, local: true) do |form| %>
			<%= form.label 'Descripción:' %>
			<%= form.text_field :description %>
			
			<br>
			<%= form.submit 'Crear', class:'btn btn-success'%>
			<%= link_to  "Volver al Home", root_path, class:'btn btn-info' %>
			<br><br>
			<% end %>
		</div>	
		
	</div>
</div>

app/views/todos/show.html.erb
<strong class="text-success"><%= notice %></strong>
<br>

<div class="col-md-10 col-xs-12 col-sm-11 center-block">
	<div class="card bg-light mb-3 text-dark">
		
		<h1>Descripción del ToDo</h1>
		<p>
			<strong>DESCRIPCIÓN:</strong>   <%= @todo.description %>
		</p>
		
		<p>
			<strong>ESTADO:</strong>  <%= @todo.completed ? 'Completado' : 'No Completado' %> 
		</p>
		
		<div>
			<%= link_to  "Volver", root_path, class:'btn btn-info' %>
		</div>
		
		
	</div>
</div>